# Generated by Django 3.1.1 on 2020-09-18 15:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('continent', models.CharField(max_length=10)),
                ('capital', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='event_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(help_text='Write the type of event, e.g. IED, protest, ambush, etc', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_org', models.CharField(help_text='Please enter the name of this organization', max_length=40)),
                ('members', models.IntegerField(null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PIR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PIR_number', models.CharField(help_text='Enter the PIR value', max_length=10)),
                ('description', models.CharField(help_text='Describe the PIR', max_length=40)),
            ],
            options={
                'verbose_name': 'PIR',
                'verbose_name_plural': 'PIR',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=40)),
                ('reliability', models.CharField(blank=True, choices=[('A', 0), ('B', 1), ('C', 2), ('D', 3), ('E', 4), ('F', 5)], max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Traffic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docname', models.CharField(default='', editable=False, help_text='Enter title of document', max_length=100)),
                ('traffic_slug', models.SlugField(max_length=250, unique_for_date='completed')),
                ('docdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(help_text='Enter the category', max_length=20)),
                ('fulltext', models.TextField(blank=True, help_text='Enter the full traffic text if possible')),
                ('grids', models.CharField(blank=True, help_text='Assign grid location', max_length=40)),
                ('status', models.CharField(choices=[('live', 'Live'), ('completed', 'Completed'), ('to_verify', 'To Verify')], default='to_verify', max_length=10)),
                ('PIR', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logger.pir')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logger.source')),
            ],
            options={
                'verbose_name': 'Traffic',
                'verbose_name_plural': 'Traffic',
                'ordering': ('-docdate',),
            },
        ),
        migrations.CreateModel(
            name='EventMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=40)),
                ('deceased', models.IntegerField()),
                ('wounded', models.IntegerField()),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logger.event_type')),
                ('reference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logger.traffic')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Please enter the name of the piece of equipment observed', max_length=40)),
                ('EqClass', models.CharField(help_text='Write the class for this piece of equipment (e.g. MBT, APC, IFV, etc.)', max_length=40)),
                ('origin_manufacture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logger.country')),
                ('unit', models.ManyToManyField(to='logger.Organizations')),
            ],
        ),
    ]
