# Generated by Django 3.1.1 on 2020-09-20 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='Nationality',
            new_name='nationality',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='EqClass',
        ),
        migrations.AddField(
            model_name='equipment',
            name='role',
            field=models.CharField(blank=True, help_text='Write the role for this piece of equipment (e.g. MBT, APC, IFV, etc.)', max_length=40),
        ),
        migrations.AddField(
            model_name='eventmatrix',
            name='actor_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attacker', to='logger.organizations'),
        ),
        migrations.AddField(
            model_name='eventmatrix',
            name='actor_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='victim', to='logger.organizations'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='origin_manufacture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logger.country'),
        ),
    ]
