# Generated by Django 3.1.1 on 2020-09-18 15:29

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='traffic',
            managers=[
                ('completed', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='traffic',
            name='docname',
            field=models.CharField(default='', help_text='Enter title of document', max_length=100),
        ),
        migrations.AlterField(
            model_name='traffic',
            name='fulltext',
            field=models.TextField(help_text='Enter the full traffic text if possible'),
        ),
    ]
