# Generated by Django 3.1.1 on 2020-09-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_auto_20200918_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traffic',
            name='traffic_slug',
            field=models.SlugField(max_length=250, unique_for_date='complete'),
        ),
    ]
