# Generated by Django 3.1.1 on 2020-09-18 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0004_auto_20200918_1208'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='traffic',
            managers=[
            ],
        ),
    ]
