# Generated by Django 3.1.1 on 2020-09-20 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0005_auto_20200918_1229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventmatrix',
            options={'verbose_name_plural': 'Event Matrix'},
        ),
        migrations.AddField(
            model_name='source',
            name='Nationality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logger.country'),
        ),
        migrations.AlterField(
            model_name='pir',
            name='PIR_number',
            field=models.CharField(help_text='Enter the PIR value', max_length=10, verbose_name='PIR Number'),
        ),
        migrations.AlterField(
            model_name='source',
            name='reliability',
            field=models.CharField(blank=True, choices=[('A', 0), ('B', 1), ('C', 2), ('D', 3), ('E', 4), ('F', 5)], max_length=40, verbose_name='Reliability level'),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_name',
            field=models.CharField(max_length=40, verbose_name='Source name'),
        ),
    ]
