# Generated by Django 3.1.1 on 2020-10-12 22:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0022_auto_20201010_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traffic',
            name='docdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 12, 18, 24, 46, 11768)),
        ),
    ]
